---
title: "Linear Regression and Broom"
teaching: 60
exercises: 20
source: Rmd
---

::::::::::::::::::::::::::::::::::::::: objectives

- To be able to explore relationships between variables
- To be able to calculate predicted variables and residuals 
- To be able to construct linear regression models
- To be able to check assumptions for linear regressiona models
- To be able to present model outcomes using Broom

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: questions

- How can I explore relationships between variables in my data?
- How can I check that my data is suitable for use in a linear regression model?
- How can I present model outputs in an easier to read way?

::::::::::::::::::::::::::::::::::::::::::::::::::

## Content

-   Linear Regression Models
-   Use of Logit
-   Assumption Diagnostics and Regression Troubleshooting 
-   Use of Broom

## Data

'''R
lon_dims_imd_2019 <- read.csv(".data/English_IMD_2019_Domains_rebased_London_by_CDRC.csv")
ahah_2022 <- read.csv('data/AHAH_V3_0.csv')

#add London Dims to AHA data
combinedLondonDims <- merge(ahah_2022,lon_dims_imd_2019,by.x="lsoa19",by.y="ls11cd",all.y

'''

We are going to use the data from the Consumer Data Research Centre, specifically the London IMD 2019 (English IMD 2019 Domains rebased) and the Access to Healthy Assets & Hazards (AHAH) 2022 data.

Atribution: Data provided by the Consumer Data Research Centre, an ESRC Data Investment: ES/L011840/1, ES/L011891/1 

The statistical unit areas across the country are Lower layer Super Output Areas (LSOAs). We have combined the data using a right join to focus on London.

